spring.application.name=Prototype

logging.charset.console=UTF-8
server.port=8082

redmine.url=http://localhost:8080
redmine.api-key=9d275dce4f74d9187f0fce0142caa737fe4f2836
redmine.project-key=support
logging.level.buzmakov.Prototype=DEBUG
